CREATE TABLE QuanLyBanHang;

USE QuanLyBanHang;

CREATE TABLE Customer(
cID   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cName VARCHAR(50),
cAge  INT NOT NULL
);

CREATE TABLE Orders(
oID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
oDate DATETIME NOT NULL,
oTotalPrice DOUBLE NOT NULL,
cId  INT NOT NULL,
FOREIGN KEY (cId) REFERENCES Customer (cID)
);

CREATE TABLE OrderDetail(
oId INT NOT NULL,
pId INT NOT NULL,
odQTY INT NOT NULL,
UNIQUE (oId, pId),
FOREIGN KEY (oId) REFERENCES Orders (oID),
FOREIGN KEY (pId) REFERENCES Product (pID)
);


CREATE TABLE Product(
pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pName VARCHAR(50),
pPrice DOUBLE
);




